---
title: "Assignment 1: Introduction"
author: "Zhaoxin Zhang"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took R courses and did some data analytics projects with R in 2022 and 2023. I learned about how to apply R to statistically analyze public policies and visualize data. I used R to map out state-level programs’ participation rates and draw regression lines to which factors might affect the results. However, I did not have previous experience with Git. I usually did work on my own computer and uploaded them, so I think I may spend time getting familiar with Git.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident about the linear model part of the course. I've done some projects with R's linear model with the analyses on probabilities. I also know how to report a result to 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel apprehensive about


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
